### ISSUE TITLE
m3u8 stream

### ISSUE THREAD

**Issue by fds39** [segler-alex/radiobrowser-api-rust#109]
A year ago, I discovered in the database a radio with a [m3u8 stream](https://www.radio-browser.info/#!/byname/lci). In fact it is a video stream from a TV channel.
Of course it's quite greedy in data but it's quite handy.
Several months ago I wanted to try the experiment on another TV channel I'm interested in. It worked for about a week, then it stopped with label 'Broken '
Today I came back without any better success.
Can you take a look at what prevents [my m3u8 stream](https://www.radio-browser.info/#!/byname/cnews) from working properly ? https://stream-11.dc3.dailymotion.com/sec(1nXeBFcLxi2SiPaUv6X4gej6lCTFYPbTylsiaBmJ0YY)/dm/3/x3b68jn/d/live-0.m3u8 (minimal 240p stream)

**Comment by segler-alex** [comment]
the stream does give me the status code for "Forbidden"
it is not reachable for me

**Comment by louis77** [comment]
hi @segler-alex 

I reopen this issue because I get issues from users of Tuner (which I'm the developer of) that they cannot play stations which have a m3u8 playlist URL. Obviously these URLs don't get resolved by radio-browser.info:
https://github.com/louis77/tuner/issues/84

This is one of the stations
https://www.radio-browser.info/history/ce14d522-526f-4143-8a15-7bc75e13c347

I've tried to find any reference in the radiobrowser repository about `m3u8` playlist support but couldn't find one. Is this something that can be added/supported? More and more stations use the `m3u8` playlist format.
