### ISSUE TITLE
remove stations with the same stream endpoint

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/radiobrowser-api-rust#16]
streams with the same endpoint in the database should be deleted
one problem would be to keep the one with the most information

**Comment by rewrib** [comment]
One could perhaps take the oldest entry and fill it up with information from all the other entries, if things like country or language are empty. 
I know this can be considered as evasion of the edit-block, but a small stream without country/language code is simply undiscoverable and doomed to be buried to death. 
With minority languages this can be exploited by adding all ten or so available radio stations, but at the same time leaving the language code out. This would make the radiobrowser project essentially useless for an entire language group. Until there is a good solution for the edit-situation, resolving this issue is dangerous.
