### ISSUE TITLE
improve api docs

### ISSUE THREAD

**Issue by segler-alex** [segler-alex/radiobrowser-api-rust#42]
some ideas:
* add sidemenu that is always visible with the document structure
* split up into more files, not one big file
* use bigger part of the screen (e.g.: left=sidemenu, center=text, right=examples)
* use some framework to make edit easier (https://crates.io/crates/mdbook, https://orchid.run/wiki/user-manual/getting-started/directory-structure, https://slatedocs.github.io/slate ...)

**Comment by segler-alex** [comment]
Thank you a lot for your help!!!
the output of slate looks really cool, and it lets the user find stuff much easier.
i always wanted to add some better examples (curl, wget,... something like that) to the docs, this seems noch much easier and better to look at.
i am in the process of migrating from github to gitlab, i think it would help with automatic building which i also feel is better in gitlab. (i have a lot of gitlab experience from my work :)
the automatic build i will find a solution for, if you just do the rest of migrating the docs, maybe add examples i cannot thank you enough.

**Comment by segler-alex** [comment]
do you think there would be license problems with bundling the output of slate with radiobrowser-api-rust?

**Comment by segler-alex** [comment]
Is the output of slate self contained? does it load stuff from the internet?

**Comment by An7ar35** [comment]
> Thank you a lot for your help!!!

Your more than welcome. This is a cool project you made! :)

> do you think there would be license problems with bundling the output of slate with radiobrowser-api-rust?

IANAL, but looking at [this](https://www.apache.org/licenses/GPL-compatibility.html), it looks like using Apache 2 in GPL should be ok as long as there is the _license_ and copyright notice_ as well as any _state changes_ made (which in our case is a little in the `config.rb` file only).

Also, the generated site (`/build/*`) is self-contained and does not look to fetch anything remote (I checked on the _dev_ > _network_ panel in FF and Opera and got no remote activity when loading `index.html`). The generated 'self-contained' site does include `slatedocs` generated JS code, CSS and some fonts though.

![image](https://user-images.githubusercontent.com/16761014/139842486-ddf6ee8d-f1e2-4cc3-8aba-d19dc35898dd.png)

> i always wanted to add some better examples (curl, wget,... something like that) to the docs, ...

There is a small-ish caveat to `slatedocs` in that regard: in order to differentiate code into the code tabs on the right, the code snippets need to be categorised with one of the [documented supported languages](https://github.com/rouge-ruby/rouge/blob/master/docs/Languages.md) for [`rouge`](https://github.com/rouge-ruby/rouge). Meaning that not all (json/xml/csv/m3u/pls/curl/wget) might be able to get their own tab since they do not all have direct support in [`rouge`](https://github.com/rouge-ruby/rouge).

Currently I am using for the tabs:
- JSON `json`
- XML: `xml`
- CSV: `shell`
- m3u/pls:  `plaintext`

In order to accommodate curl, wget, and shell based command `csv` would need to go somewhere else and shell-based example would need to be grouped together too. 
On the other hand, `http` could be used to display generic HTTP `GET` request method examples though.?

Let me know what categories (tab) you'd like based on that and I'll edit/add as required.

**Comment by phranck** [comment]
> I've copied/adapted everything over to `slatedocs` in a [branch](https://github.com/An7ar35/radiobrowser-api-rust/tree/documentation) for preview.

Slate is great. I used it to build the [API documentation](https://developer.arylic.com/httpapi) for [Arylic's DIY audio](https://www.arylic.com/collections/diy-audio) boards. The original and very outdated documentation came from Linkplay (the producer of white label hardware which Arylic uses) as a very ugly PDF. So I transferred everything to Slate initially. Now I work very close with Arylic and the documentation becomes more and more useful for developers (and even more up to date). The built in search function is a real plus!

So, I would say Slate is very good choice for documenting an API. 👍🏼
